# Generated by Django 4.2.4 on 2024-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(default=0, max_length=256),
        ),
    ]
