# Generated by Django 4.2.4 on 2024-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_recipe_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
